# lancé par cron-job.org
name: Députés

on:
 # schedule:
  
 #   - cron: '30 9,12,15,18 * * *'
  workflow_dispatch:

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd deputes
          pip install pandas tweepy python-dotenv

      - name: Post tweet
        run: |
          cd deputes
          python deputes.py
        env:
          DEPUTE_ACCESS_KEY: ${{ secrets.DEPUTE_ACCESS_KEY }}
          DEPUTE_ACCESS_SECRET: ${{ secrets.DEPUTE_ACCESS_SECRET }}
          DEPUTE_CONSUMER_KEY: ${{ secrets.DEPUTE_CONSUMER_KEY }}
          DEPUTE_CONSUMER_SECRET: ${{ secrets.DEPUTE_CONSUMER_SECRET }}

       - name: Save history update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add deputes/tweeted_deputes.txt
          git add deputes/log.log
          
          if ! git diff --quiet --staged; then
            git commit -m "🤖 Députés: Mise à jour de la liste"
            
            # Boucle pour gérer les conflits de push simultanés
            for i in {1..5}; do
              git pull --rebase origin main
              if git push; then
                echo "Push réussi !"
                exit 0
              fi
              echo "Échec du push, nouvelle tentative dans 5 secondes..."
              sleep 5
            done
            exit 1
          fi
