name: Fuseaux Bot

on:
  workflow_dispatch:
  schedule:
    # Toutes les 6 heures de 6h à 20h UTC
    - cron: "24 11 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    # Cette section est CRUCIALE pour corriger l'erreur 403 (Permission denied)
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd fuseaux
          pip install tweepy pytz

      - name: Run bot
        run: |
          cd fuseaux
          python fuseauxavecmaps.py
        env:
          HORAIRES_CONSUMER_KEY: ${{ secrets.HORAIRES_CONSUMER_KEY }}
          HORAIRES_CONSUMER_SECRET: ${{ secrets.HORAIRES_CONSUMER_SECRET }}
          HORAIRES_ACCESS_KEY: ${{ secrets.HORAIRES_ACCESS_KEY }}
          HORAIRES_ACCESS_SECRET: ${{ secrets.HORAIRES_ACCESS_SECRET }}

      - name: Save history update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add fuseaux/tweeted_territories.txt
          git add fuseaux/time_bot.log
          # On vérifie s'il y a eu un changement
          if ! git diff --quiet --staged; then
            git commit -m "🤖 Fuseaux : Mise à jour de la liste"
            # SÉCURITÉ : On récupère les modifs des autres bots avant de pousser
            git pull --rebase origin main
            git push
          fi
