name: Fuseaux Bot

on:
  workflow_dispatch:
  schedule:
    # Toutes les 2 heures de 6h à 20h UTC
    - cron: "0 6-20/2 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Version stable mise à jour
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd fuseaux
          pip install tweepy pytz

      - name: Run bot
        run: |
          cd fuseaux
          python fuseaux.py
        env:
          HORAIRES_CONSUMER_KEY: ${{ secrets.HORAIRES_CONSUMER_KEY }}
          HORAIRES_CONSUMER_SECRET: ${{ secrets.HORAIRES_CONSUMER_SECRET }}
          HORAIRES_ACCESS_KEY: ${{ secrets.HORAIRES_ACCESS_KEY }}
          HORAIRES_ACCESS_SECRET: ${{ secrets.HORAIRES_ACCESS_SECRET }}

      - name: Save History Update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # On ajoute spécifiquement le fichier d'historique dans le dossier fuseaux
          git add fuseaux/tweeted_territories.txt
          # On commit seulement s'il y a des changements
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Fuseaux: Mise à jour de l'historique des territoires" && git push)
          
