name: Histoire Bot

on:
  schedule:
    # À 15h54
    - cron: '54 15 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install tweepy python-dotenv

      - name: Run bot
        env:
          # Assure-toi que ces secrets sont bien configurés dans ton repo
          CONSUMER_KEY: ${{ secrets.HISTOIRE_CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.HISTOIRE_CONSUMER_SECRET }}
          ACCESS_KEY: ${{ secrets.HISTOIRE_ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.HISTOIRE_ACCESS_SECRET }}
        run: python histoire.py
        working-directory: ./histoire

      - name: Save history update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add histoire/index.txt
          git add histoire/log.log
          # On vérifie s'il y a eu un changement
          if ! git diff --quiet --staged; then
            git commit -m "🤖 Histoire : Mise à jour de la liste"
            # SÉCURITÉ : On récupère les modifs des autres bots avant de pousser
            git pull --rebase origin main
            git push
          fi

