name: Twitter Bot - Maires

on:
  schedule:
    - cron: '0 8,11,14,17,20 * * *'
    - cron: '30 9,12,15,18 * * *'
  workflow_dispatch:

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd maires
          pip install pandas tweepy python-dotenv

      - name: Post tweet
        run: |
          cd maires
          python maires.py
        env:
          QUIESTLEMAIRE_ACCESS_KEY: ${{ secrets.QUIESTLEMAIRE_ACCESS_KEY }}
          QUIESTLEMAIRE_ACCESS_SECRET: ${{ secrets.QUIESTLEMAIRE_ACCESS_SECRET }}
          QUIESTLEMAIRE_CONSUMER_KEY: ${{ secrets.QUIESTLEMAIRE_CONSUMER_KEY }}
          QUIESTLEMAIRE_CONSUMER_SECRET: ${{ secrets.QUIESTLEMAIRE_CONSUMER_SECRET }}

      - name: Save history update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add maires/tweeted_maires.txt
          git add maires/log.log
          # On vérifie s'il y a eu un changement
          if ! git diff --quiet --staged; then
            git commit -m "🤖 Maires : Mise à jour de la liste"
            # SÉCURITÉ : On récupère les modifs des autres bots avant de pousser
            git pull --rebase origin main
            git push
          fi
          
