name: Pollution Bot

on:
  workflow_dispatch:
  schedule:
    # On se base sur l'heure d'été (UTC+2)
    # 8h FR -> 6h UTC / 12h FR -> 10h UTC / 18h FR -> 16h UTC
    - cron: "0 6 * * *"
    - cron: "0 10 * * *"
    - cron: "0 16 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pollution # Dossier où se trouve ton script
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install tweepy requests pytz

      - name: Run bot
        run: python pollution.py
        env:
          POLLUTION_CONSUMER_KEY: ${{ secrets.POLLUTION_CONSUMER_KEY }}
          POLLUTION_CONSUMER_SECRET: ${{ secrets.POLLUTION_CONSUMER_SECRET }}
          POLLUTION_ACCESS_KEY: ${{ secrets.POLLUTION_ACCESS_KEY }}
          POLLUTION_ACCESS_SECRET: ${{ secrets.POLLUTION_ACCESS_SECRET }}
          POLLUTION_AIRVISUAL_API_KEY: ${{ secrets.POLLUTION_AIRVISUAL_API_KEY }}
          
