name: TwittHeure - Heures Aléatoires

on:
  workflow_dispatch:
#  schedule:
    #  past the hour, every 3 hours, between 04:00 and 20:59
 #   - cron: "39 4-20/3 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd twittheure
          pip install tweepy pytz

      - name: Run bot
        run: |
          cd twittheure
          python twittheure_random.py
        env:
          THeure_CONSUMER_KEY: ${{ secrets.THEURE_CONSUMER_KEY }}
          THeure_CONSUMER_SECRET: ${{ secrets.THEURE_CONSUMER_SECRET }}
          THeure_ACCESS_KEY: ${{ secrets.THEURE_ACCESS_KEY }}
          THeure_ACCESS_SECRET: ${{ secrets.THEURE_ACCESS_SECRET }}
