name: TwittHeure - Heures Fixes

on:
  workflow_dispatch:
  schedule:
    # Crons calés sur l'heure d'été (UTC+2) Décommenter les cron si réutilisation de ce fichier.
   # - cron: "59 21 * * *"     # 22h UTC → 00h00 FR (été) / attend 1h → 00h00 FR (hiver)
   # - cron: "11 9 * * *"     # 9h11 UTC → 11h11 FR (été) / attend 1h → 11h11 FR (hiver)
   # - cron: "22 20 * * *"    # 20h22 UTC → 22h22 FR (été) / attend 1h → 22h22 FR (hiver)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd twittheure
          pip install tweepy pytz

      - name: Run bot
        run: |
          cd twittheure
          python twittheure_fixe.py
        env:
          THeure_CONSUMER_KEY: ${{ secrets.THEURE_CONSUMER_KEY }}
          THeure_CONSUMER_SECRET: ${{ secrets.THEURE_CONSUMER_SECRET }}
          THeure_ACCESS_KEY: ${{ secrets.THEURE_ACCESS_KEY }}
          THeure_ACCESS_SECRET: ${{ secrets.THEURE_ACCESS_SECRET }}
