name: TwittHeure - Heures Aléatoires

on:
  workflow_dispatch:
  schedule:
    # Se lance toutes les 15 min de 4h à 21h UTC (couvre 6h-23h FR été/hiver)
    - cron: "*/15 4-21 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: twittheure
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install tweepy pytz
      - name: Run random hours
        run: python twittheure_random.py
        env:
          THeure_CONSUMER_KEY: ${{ secrets.THEURE_CONSUMER_KEY }}
          THeure_CONSUMER_SECRET: ${{ secrets.THEURE_CONSUMER_SECRET }}
          THeure_ACCESS_KEY: ${{ secrets.THEURE_ACCESS_KEY }}
          THeure_ACCESS_SECRET: ${{ secrets.THEURE_ACCESS_SECRET }}
          
