name: ZemmourBot Action

on:
  schedule:
    # Déclenchements à 08:00 et 15:00 UTC
    - cron: '0 8,15 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install tweepy

      - name: Run bot
        env:
          ZEMMOUR_CONSUMER_KEY: ${{ secrets.ZEMMOUR_CONSUMER_KEY }}
          ZEMMOUR_CONSUMER_SECRET: ${{ secrets.ZEMMOUR_CONSUMER_SECRET }}
          ZEMMOUR_ACCESS_TOKEN: ${{ secrets.ZEMMOUR_ACCESS_TOKEN }}
          ZEMMOUR_ACCESS_TOKEN_SECRET: ${{ secrets.ZEMMOUR_ACCESS_TOKEN_SECRET }}
        run: python zemmour/zemmour.py

      - name: Update Repository (Index)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          # On ajoute le nouveau fichier index.json
          git add zemmour/index.json
          # On commit seulement s'il y a des changements
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update index [skip ci]" && git push)

